### App is working message
GET http://localhost:3000
Content-Type: application/json

### Show all users
GET http://localhost:3000/users/
Content-Type: application/json


### Show one user
GET http://localhost:3000/users/11c27e1a-7cd7-4baf-b106-83f1e260cb4a
Content-Type: application/json


### Search for users
GET http://localhost:3000/users/
Content-Type: application/json


### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "name": "teste",
    "password": "12345678dfgdfgdfgfdgfdgdfgdfgdfgdfg"
}


### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "mulan@gmail.com",
    "password": "12345678dfgdfgdfgfdgfdgdfgdfgdfgdfg"
}


### Update user
PUT http://localhost:3000/users/11c27e1a-7cd7-4baf-b106-83f1e260cb4a
Content-Type: application/json

{
    "name": "Ryan Dhawl",
    "email": "ryan@gmail.com",
    "password": "12345"
}


### Delete user
DELETE http://localhost:3000/users/d3120fd4-bbe4-4206-b43e-a6469122261b
