### App is working message
GET http://localhost:3000
Content-Type: application/json

### Show all users
GET http://localhost:3000/users/
Content-Type: application/json


### Show one user
GET http://localhost:3000/users/11c27e1a-7cd7-4baf-b106-83f1e260cb4a
Content-Type: application/json


### Search for users
GET http://localhost:3000/users/
Content-Type: application/json


### Create new user
POST http://localhost:3000/users/
Content-Type: application/json

{
    "email": "teste4@gmail.com",
    "name": "teste",
    "password": "12345678"
}


### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "teste2@gmail.com",
    "password": "12345678"
}


### Update user
PUT http://localhost:3000/users/a63e1ea1-bb09-4c7b-b851-255169ce3c3b
Content-Type: application/json

{
    "name": "Mark Zuckerberg 2",
    "email": "mark@gmail.com",
    "password": "12345"
}


### Delete user
DELETE http://localhost:3000/users/6bda6a87-52f2-43b0-aad2-93c0a9ffd30b
